---
title: 'Exercises'
output: 
  html_document:
    toc: false
---

```{r setup-ex, include=FALSE}
library(knitr)
library(stringr)
knitr::opts_chunk$set(message=FALSE, warning=FALSE, eval=TRUE, echo=FALSE)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stringr))
source('reveal.R')
```

\  


These exercises will help gauge your understanding of the material covered during this course. Each exercise contains a series of questions which will help reinforce statistical theory, how to implement this theory in R and also take you through a typical workflow when asking and answering research questions with your data. 

Whilst working through the exercises we recommend that you create a new R script for each exercise in an RStudio project. Make sure you include plenty of comments and notes to yourself for future reference, or, perhaps even better, include your code and commentary in an R markdown document. Of course, how you want to work is entirely up to you!

During each exercise you will be working in a synchronous session on Blackboard collaborate where you will be able to ask questions and get one-to-one help from the course instructors. Towards the end of each session, one of the instructors will go through each exercise with you in real time to help clear up any lingering doubts and also provide you with an opportunity to discuss analytical decisions.

You can check the [solutions to the exercises](exercise_solutions.html){target="_blank"} after each of our synchronous sessions. 

Have fun!

\  

### Day 1

 - [Poisson GLM exercise](GLM_1_Poisson_exercise.html)

\  
 
### Day 2
 
 - [Binomial GLM exercise](GLM_2_Binomial_exercise.html)
 
\  

### Day 3

 - [Bernoulli GLM exercise](GLM_3_Bernoulli_exercise.html)
 
\  

