---
title: "Exercise Solutions"
output: 
  html_document:
    toc: false
---

```{r setup-alex, include=FALSE}
library(knitr)
library(stringr)
knitr::opts_chunk$set(message=FALSE, warning=FALSE, eval=TRUE, echo=FALSE)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stringr))
source('reveal.R')
```

\  

Follow the links below for solutions to each of the exercises you have completed on this course. Click on the 'code' buttons to reveal the R code associated with each question.

\  

### Day 1

```{r sol_GDE, results='asis', eval = isTRUE(show_text_GDE)}
link_name <- "GLM - Poisson exercise"
file_name <- "GLM_1_Poisson_exercise_solutions"
paste0("- [", link_name, "](", file_name, ".html)") %>%
cat(sep="\n\n")
```

\  

### Day 2

```{r sol_lm1, results='asis', eval = isTRUE(show_text_lm1)}
link_name <- "GLM - binomial (0/1 data) exercise: Rays maturity"
file_name <- "GLM_2_Binomial_RayBin_exercise_solutions"
paste0("- [", link_name, "](", file_name, ".html)") %>%
cat(sep="\n\n")

link_name <- "GLM - binomial (0/1 data) optional exercise #1: Dolphins activity"
file_name <- "GLM_2_Optional_Binomial_Dolphins_exercise_solutions"
paste0("- [", link_name, "](", file_name, ".html)") %>%
cat(sep="\n\n")

link_name <- "GLM - binomial (0/1 data) optional exercise #2: Dolphins extension"
file_name <- "GLM_2_Optional_Binomial_Dolphins_extension_exercise_solutions"
paste0("- [", link_name, "](", file_name, ".html)") %>%
cat(sep="\n\n")
```

\  

### Day 3

```{r sol_lm2, results='asis', eval = isTRUE(show_text_lm2)}
link_name <- "GLM - binomial (proportion data) exercise"
file_name <- "GLM_3_BinomialProportions_exercise_solutions"
paste0("- [", link_name, "](", file_name, ".html)") %>%
cat(sep="\n\n")
```

\  

```{r code-out, include = FALSE}
<<<<<<< HEAD
sol_files<- list.files(pattern= "_exercise_solutions.Rmd", full.names= F)

for(i in sol_files){
  knitr::purl(i, output = paste0('./exercise_solutions/', substr(i, 1, nchar(i)-4), '.R'), quiet = TRUE)
}
=======
# TODO: generate list automagically
setwd('./exercise_solutions')
knitr::purl('../GLM_1_Poisson_exercise_solutions_v2.Rmd', output = 'GLM_1_Poisson_exercise_solutions_v2.R', quiet = TRUE)
knitr::purl('../GLM_2_Binomial_exercise_solutions_v2.Rmd', output = 'GLM_2_Binomial_exercise_solutions_v2.R', quiet = TRUE)
knitr::purl('../GLM_3_BinomialProportions_exercise_solutions.Rmd', output = 'GLM_3_BinomialProportions_exercise_solutions.R', quiet = TRUE)
setwd('..')
>>>>>>> e9d0d088b8e4193ad8dcc3d94c263a53cadf511a
```
