---
title: 'Syllabus'
output: 
  html_document:
    toc: false
---

\  

The course will start at 09:30 each morning and finish at 17:00. We will break for a one hour lunch break around 12:30. However, everyone learns R and statistics in their own way and at their own pace so this syllabus should be treated as indicative rather than absolute. There will also be plenty of opportunities to take short breaks during the course.

The live sessions will be held on Blackboard Collaborate at the time indicated in the timetable below. The recorded video lectures will be hosted on MyAberdeen and you should watch them at the time indicated below.

<!--All teaching will be held in room FN113 in the Fraser Noble building (building No. 7 on [this map](images/uoa_map.png){target="_blank"} on the old Aberdeen campus).
-->

\  

#### Wednesday 28^th^ April 2021

\  

|09:30 - 10:00 | 10:00 - 12:30 | 12:30 - 13:30 |13:30 - 17:00 |
|:-------------|:-------------|:------------|:-------------|
| Course introduction (live - TC)  | Introducing Generalized Linear Models, using the Poisson GLM, theory lecture (recorded) | LUNCH |Poisson GLM live practical and review session (TC)|

\  

\  

#### Thurday 29^th^ April 2021 

\  

|09:30 - 12:30     | 12:30 - 13:30 |13:30 - 17:00    | 
|:-----------------|:-------------|:---------------|
|GLM for binary (0/1) data, theory lecture (recorded)|LUNCH|GLM for binary (0/1) data live practical (TC)|

\  

\  

#### Friday 30^th^ April 2021

\  

|09:30 - 11:30               | 11:30 - 12:30     | 12:30 - 13:30 |13:30 - 16:00    | 16:10 - 17:00      |
|:--------------------------|:-----------------|:-------------|:---------------|:------------------|
|Introducing binomial GLMs for estimating proportions, theory lecture (recorded)| GLM for binary (0/1) data - live review session (TC) | LUNCH |Binomial GLM for proportions - live practical and review session (TC)| Question and answer session on LM and GLM (AD & TC)|

\  

